title: "Kim Ma"
email: phuongkim.ma@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 This is my personal portfolio, based on the template from MLH Fellowship portfolio template to show up my works.
baseurl: "/" 
url: "https://mkimp.github.io/" 
twitter_username: none
github_username:  mKimp

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
